# Generated by Django 5.1.5 on 2025-02-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.PositiveBigIntegerField()),
                ('decs', models.TextField()),
                ('pic', models.ImageField(upload_to='products/')),
                ('stock', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
